# Generated by Django 4.2.9 on 2024-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contactus1",
        ),
    ]
