# Generated by Django 4.2.9 on 2024-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_contactrequest_delete_contactus1"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="name",
            field=models.TextField(default="nae"),
            preserve_default=False,
        ),
    ]
