# Generated by Django 4.2.9 on 2024-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_contactrequest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mealFilePath', models.CharField(max_length=200)),
            ],
        ),
    ]
