# Generated by Django 4.2.9 on 2024-01-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hostelmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelmeal',
            name='hostelId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.hostel'),
            preserve_default=False,
        ),
    ]
