# Generated by Django 4.2.9 on 2024-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_hostelmeal_hostelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
