# Generated by Django 4.2.9 on 2024-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
