# Generated by Django 4.2.9 on 2024-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_orderhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='admin_message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
